package com.example.server.enumeration;

public enum KeyUsages {
    DIGITAL_SIGNATURE, NON_REPUDIATION, KEY_ENCIPHERMENT,  DATA_ENCIPHERMENT, KEY_AGREEMENT, KEY_CERT_SIGN, CRL_SIGN, ENCIPHER_ONLY,  DECIPHER_ONLY
}
