export const SET_KEYUSAGES = "SET_KEYUSAGES";

export const SET_ALL_CERTIFICATES = "SET_ALL_CERTIFICATES";
export const SET_ALL_REVOCATED_CERTS = "SET_ALL_REVOCATED_CERTS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGOUT = "USER_LOGOUT";
